/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        JButton botonesT[] = {cmdCrear, cmdLimpiar};
        JButton botonesF[] = {cmdLlenadoMa, cmdLlenadoAuto, cmdOp};
        Helper.habilitarBotones(botonesT);
        Helper.deshabilitarBotones(botonesF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumFi = new javax.swing.JTextField();
        txtNumCol = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoMa = new javax.swing.JButton();
        cmdLlenadoAuto = new javax.swing.JButton();
        cmdOp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablainicial = new javax.swing.JTable();
        cmbOperacion = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaResultado = new javax.swing.JTable();
        cmdLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Iniciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No. filas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 31, -1, -1));

        jLabel2.setText("No. columnas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 86, -1, -1));

        txtNumFi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFiActionPerformed(evt);
            }
        });
        txtNumFi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumFiKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumFi, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 27, 130, -1));

        txtNumCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumColActionPerformed(evt);
            }
        });
        txtNumCol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumColKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 260, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cmdLlenadoMa.setText("Llenado Manual");
        cmdLlenadoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoMaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmdLlenadoAuto.setText("Llenado Automatico");
        cmdLlenadoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        cmdOp.setText("Operacion");
        cmdOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOpActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 290, 140));

        tblTablainicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTablainicial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 330, 280));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagonal Secundaria", "Triangular Superior", "Triangular Inferior", "Matriz Traspuesta", "Letra A", "Letra Z", "Letra T", "Letra V", "Letra E", "Letra F", "Letra P", "Letra I", "Letra N", "Letra Y", "Letra X" }));
        cmbOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 80, -1));

        tblTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaResultado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 320, 280));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Matrices ,letras y otros");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(804, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumColActionPerformed

    private void cmdOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOpActionPerformed
        int nf, nc, op;

        nf = Integer.parseInt(txtNumFi.getText());
        nc = Integer.parseInt(txtNumCol.getText());
        op = cmbOperacion.getSelectedIndex();
        Helper.limpiadoTabla(tblTablaResultado);

        switch (op) {
            case 0:
                Helper.diagonalSecundaria(tblTablainicial, tblTablaResultado);
                break;
            case 1:
                Helper.triangularSuperior(tblTablainicial, tblTablaResultado);
                break;
            case 2:
                Helper.triangularInferior(tblTablainicial, tblTablaResultado);
                break;
            case 3:
                Helper.matrizTraspuesta(tblTablainicial, tblTablaResultado);
                break;
            case 4:
                Helper.letraA(tblTablainicial, tblTablaResultado);
                break;
            case 5:
                Helper.letraZ(tblTablainicial, tblTablaResultado);
                break;
            case 6:
                Helper.letraT(tblTablainicial, tblTablaResultado);
                break;
            case 7:
                Helper.letraV(tblTablainicial, tblTablaResultado);
                break;
            case 8:
                Helper.letraE(tblTablainicial, tblTablaResultado);
                break;
            case 9:
                Helper.letraF(tblTablainicial, tblTablaResultado);
                break;
            case 10:
                Helper.letraP(tblTablainicial, tblTablaResultado);
                break;
            case 11:
                Helper.letraI(tblTablainicial, tblTablaResultado);
                break;
            case 12:
                Helper.letraN(tblTablainicial, tblTablaResultado);
                break;
            case 13:
                Helper.letraY(tblTablainicial, tblTablaResultado);
                break;
            case 14:
                Helper.letraX(tblTablainicial, tblTablaResultado);
                break;

        }
        JButton botonesH[] = {cmdOp, cmdLimpiar};
        JButton botonesD[] = {cmdLlenadoAuto, cmdLlenadoMa};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);


    }//GEN-LAST:event_cmdOpActionPerformed

    private void cmbOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionActionPerformed

    }//GEN-LAST:event_cmbOperacionActionPerformed

    private void cmdLlenadoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutoActionPerformed

        int nf, nc, n;

        nc = tblTablainicial.getColumnCount();
        nf = tblTablainicial.getRowCount();

        Helper.mensaje(this, "Matriz llenada exitosamente.", 1);

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablainicial.setValueAt(n, i, j);
            }
        }

        JButton botonesH[] = {cmdOp, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdLlenadoAuto, cmdLlenadoMa};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLlenadoAutoActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        int nc, nf;

        nc = tblTablainicial.getColumnCount();
        nf = tblTablainicial.getRowCount();
        DefaultTableModel tm, tm2;
        txtNumFi.setText("");
        txtNumCol.setText("");
        txtNumFi.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);

        Helper.porDefectoTabla(tblTablainicial);
        Helper.porDefectoTabla(tblTablaResultado);

        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdLlenadoAuto, cmdLlenadoMa, cmdOp};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed

        try {
            int nc, nf;
            DefaultTableModel tm, tm2;
            nf = Integer.parseInt(txtNumFi.getText());
            nc = Integer.parseInt(txtNumCol.getText());
            tm = (DefaultTableModel) tblTablainicial.getModel();
            tm2 = (DefaultTableModel) tblTablaResultado.getModel();
            
            if (nf < 10 || nc < 10) {
                Helper.mensaje(this, "Por favor considere 15 como el mínimo para filas y columnas.", 2);
                txtNumFi.setText("");
                txtNumCol.setText("");
                txtNumFi.requestFocusInWindow();
            } else if (nf > 12 || nc > 12) {
                Helper.mensaje(this, "Por favor considere 12 como el máximo para filas y columnas.", 2);
                txtNumFi.setText("");
                txtNumCol.setText("");
                txtNumFi.requestFocusInWindow();
            } else {
                Helper.mensaje(this, "Matriz creada exitosamente.", 1);
                tm.setRowCount(nf);
                tm.setColumnCount(nc);
                tm2.setRowCount(nf);
                tm2.setColumnCount(nc);
                
    
            }
        } catch (NumberFormatException e) {
            Helper.mensaje(this, "Campos No validos por favor ingreser Datos otra vez", 3);
            txtNumFi.setText("");
            txtNumCol.setText("");
            txtNumFi.requestFocusInWindow();
        }

        JButton botonesH[] = {cmdLimpiar,cmdLlenadoMa, cmdLlenadoAuto};
        JButton botonesD[] = {cmdOp, cmdCrear};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoMaActionPerformed
        int nf, nc;
        int n, sw, res;
        nf = tblTablainicial.getRowCount();
        nc = tblTablainicial.getColumnCount();
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elemento en la posición [" + i + "]" + "[" + j + "]").trim());
                        tblTablainicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un número válido", 3);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Estás seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            Helper.mensaje(this, "Debe llenar la matriz.", 2);
                            sw = 1;
                            i = nf;
                            j = nc;

                            Helper.limpiadoTabla(tblTablainicial);
                            Helper.limpiadoTabla(tblTablaResultado);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }

        JButton botonesH[] = {cmdOp, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdLlenadoAuto, cmdLlenadoMa};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLlenadoMaActionPerformed

    private void txtNumFiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFiActionPerformed

    private void txtNumFiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumFiKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
    }//GEN-LAST:event_txtNumFiKeyTyped

    private void txtNumColKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumColKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
    }//GEN-LAST:event_txtNumColKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenadoAuto;
    private javax.swing.JButton cmdLlenadoMa;
    private javax.swing.JButton cmdOp;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaResultado;
    private javax.swing.JTable tblTablainicial;
    private javax.swing.JTextField txtNumCol;
    private javax.swing.JTextField txtNumFi;
    // End of variables declaration//GEN-END:variables
}
